 
 source "http://rubygems.org"

 require "rubygems"
 require "bundler/setup"



 gem "awesome_print"
 require "csv"
 require  File.join( Bundler.root , "character_details.rb" )
 require  File.join( Bundler.root , "regex_character_sets.rb" )